adrianb11_listmanager_manage:
    path: /listmanager
    defaults: { _controller: adrianb11.listmanager.controller.board.manage:handle }

adrianb11_listmanager_add_board:
    path: /listmanager/add
    defaults: { _controller: adrianb11.listmanager.controller.board.manage:add_board }

adrianb11_listmanager_remove_board:
    path: /listmanager/remove/{id}
    defaults: { _controller: adrianb11.listmanager.controller.board.manage:remove_board }
