services:
    adrianb11.listmanager.controller.board.manage:
        class: adrianb11\listmanager\controller\board_manage_controller
        arguments:
            - '@controller.helper'
            - '@template'
            - '@auth'
            - '@dbal.conn'
            - '@path_helper'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'

    adrianb11.listmanager.listener:
        class: adrianb11\listmanager\event\main_listener
        arguments:
            - '@language'
            - '@controller.helper'
            - '@template'
            - '@request'
            - '@adrianb11.listmanager.boards'
            - '@auth'
        tags:
            - { name: event.listener }

    adrianb11.listmanager.boards:
        class: adrianb11\listmanager\core\boards
        arguments:
            - '@template'
            - '@content.visibility'
            - '@auth'
            - '@user'
            - '@dbal.conn'
            - '@cache'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
